"""Central workflow defaults.

YAML files should only override experiment-specific values. Defaults that are
stable across datasets and experiments live here.
"""

from __future__ import annotations

try:
    from yacs.config import CfgNode as CN
except ImportError as exc:  # pragma: no cover - environment contract
    raise ImportError(
        "Re-id-Project requires 'yacs' for its workflow configuration. "
        "Create the environment from environment.yml or install yacs."
    ) from exc


_C = CN()

_C.PROJECT = "reid_project"
_C.WORK_DIR = ""
_C.ROOT_DIR = ""

_C.EXPERIMENT = CN()
_C.EXPERIMENT.JOB_ID = ""
_C.EXPERIMENT.TRAIN_JOB_ID = ""
_C.EXPERIMENT.PROTOCOL_HASH = ""
_C.EXPERIMENT.CONDITION = ""
_C.EXPERIMENT.SOURCE = ""
_C.EXPERIMENT.TEST_SESSION = ""
_C.EXPERIMENT.DATA_MANIFEST_HASH = ""
_C.EXPERIMENT.RUN_RECORD = ""

_C.PATHS = CN()
_C.PATHS.DATA_HOME = "/data/fzliang/reid-project"
_C.PATHS.DATA_ROOT = ""
_C.PATHS.TRAIN_CSV = ""
_C.PATHS.VAL_CSV = ""
_C.PATHS.TEST_CSV = ""

_C.PREPROCESS = CN()
_C.PREPROCESS.DATASET = ""
_C.PREPROCESS.MODE = "raw"
_C.PREPROCESS.OUTPUT_FORMAT = ""
_C.PREPROCESS.RAW_ROOT = ""
_C.PREPROCESS.EXTRACTED_ROOT = ""
_C.PREPROCESS.POSE2D_OUTPUT_ROOT = ""
_C.PREPROCESS.OUTPUT = ""
_C.PREPROCESS.PREPARED_ROOT = ""
_C.PREPROCESS.REUSE_PREPARED = False
_C.PREPROCESS.CAMERA = "cam1"
_C.PREPROCESS.IMU_SOURCE = ""
_C.PREPROCESS.EGOHUMANS_ROOT = ""
_C.PREPROCESS.SYNTHETIC_IMU_ROOT = ""
_C.PREPROCESS.SYNTHETIC_IMU_SIDE = ""
_C.PREPROCESS.SKELETON_SOURCE = "vicon"
_C.PREPROCESS.POSE2D_TO_SKELETON = False
_C.PREPROCESS.SKELETON_NORMALIZE = False
_C.PREPROCESS.IMU = CN()
_C.PREPROCESS.IMU.LOWPASS_CUTOFF_HZ = None
_C.PREPROCESS.IMU.LOWPASS_FS_HZ = 30.0
_C.PREPROCESS.IMU.SENSOR = ""
_C.PREPROCESS.IMU.OUTPUT_FORMAT = "legacy_48d"

_C.EXTRACT = CN()
_C.EXTRACT.DETECTOR = "bytetrack"
_C.EXTRACT.TRACKER = "bytetrack"
_C.EXTRACT.POSE_ESTIMATOR = "alphapose"
_C.EXTRACT.VIDEO = ""
_C.EXTRACT.MANIFEST_CSV = ""
_C.EXTRACT.RESULTS_ROOT = ""
_C.EXTRACT.COPY_FROM = ""
_C.EXTRACT.BYTETRACK_PYTHON = ""
_C.EXTRACT.ALPHAPOSE_PYTHON = ""
_C.EXTRACT.BYTETRACK_ROOT = ""
_C.EXTRACT.BYTETRACK_EXP_FILE = ""
_C.EXTRACT.BYTETRACK_CKPT = ""
_C.EXTRACT.BYTETRACK_CONF = 0.1
_C.EXTRACT.BYTETRACK_NMS = 0.7
_C.EXTRACT.BYTETRACK_TSIZE = 640
_C.EXTRACT.BYTETRACK_FP16 = False
_C.EXTRACT.BYTETRACK_FUSE = False
_C.EXTRACT.BYTETRACK_MOT20 = False
_C.EXTRACT.BYTETRACK_MIN_BOX_AREA = 10.0
_C.EXTRACT.BYTETRACK_ASPECT_RATIO_THRESH = 1.6
_C.EXTRACT.ALPHAPOSE_ROOT = ""
_C.EXTRACT.ALPHAPOSE_CFG = ""
_C.EXTRACT.ALPHAPOSE_CKPT = ""
_C.EXTRACT.DETBATCH = None
_C.EXTRACT.POSEBATCH = None
_C.EXTRACT.HEADLESS = True
_C.EXTRACT.USE_EXPANDABLE_SEGMENTS = False
_C.EXTRACT.LIMIT = 0
_C.EXTRACT.SKIP_EXISTING = True
_C.EXTRACT.REUSE_EXISTING = True
_C.EXTRACT.FORCE = False
_C.EXTRACT.INVALID_CACHE_POLICY = "error"
_C.EXTRACT.GPU = 0
_C.EXTRACT.MERGE_TRACKLETS = CN()
_C.EXTRACT.MERGE_TRACKLETS.ENABLED = False
_C.EXTRACT.MERGE_TRACKLETS.MAX_GAP = 10000000
_C.EXTRACT.MERGE_TRACKLETS.SCORE_THRESH = 2.2
_C.EXTRACT.MERGE_TRACKLETS.MAX_NORM_DIST = 2.8
_C.EXTRACT.MERGE_TRACKLETS.MAX_SIZE_DIFF = 1.8
_C.EXTRACT.MERGE_TRACKLETS.FILL_GAPS = False
_C.EXTRACT.MERGE_TRACKLETS.KNOWN_NUM_PEOPLE = 1

_C.SLICE = CN()
_C.SLICE.ROOT = ""
_C.SLICE.OUT_DIR = ""
_C.SLICE.SKELETON_ROOT = ""
_C.SLICE.SKELETON_SOURCE = "vicon"
_C.SLICE.SKELETON_NORMALIZE = True
_C.SLICE.WINDOW_LEN = 24
_C.SLICE.STRIDE = 16
_C.SLICE.SENSOR_ORDER = []
_C.SLICE.SPLIT_POLICY = ""
_C.SLICE.TRAIN_SUBJECTS = ()
_C.SLICE.VAL_SUBJECTS = ()
_C.SLICE.TEST_SUBJECTS = ()
_C.SLICE.TRAIN_SESSIONS = ()
_C.SLICE.VAL_SESSIONS = ()
_C.SLICE.TEST_SESSIONS = ()
_C.SLICE.MAX_SEQUENCES = 0
_C.SLICE.MULTI_PERSON = False
_C.SLICE.SEGMENT_ROOT = ""
_C.SLICE.OUTPUT_ROOT = ""
_C.SLICE.CUSTOM_IMU_ROOT = ""
_C.SLICE.RAW_IMU_ROOT = ""
_C.SLICE.RAW_SWAP_SESSIONS = ""
_C.SLICE.LEGACY_SENSOR = "L_LowArm"
_C.SLICE.FORCE = False
_C.SLICE.FOLDS = []
_C.SLICE.FRAME_ACC_CANDIDATE_GROUP_SIZE = 0
_C.SLICE.REQUIRE_MULTI_CANDIDATE_TEST = False

_C.TRAIN = CN()
_C.TRAIN.EPOCHS = 50
_C.TRAIN.BATCH_SIZE = 96
_C.TRAIN.NUM_WORKERS = 8
_C.TRAIN.COMPUTE_IMU_STATS = True
_C.TRAIN.IMU_STATS_JSON = ""
_C.TRAIN.PER_SESSION_STATS_DIR = ""
_C.TRAIN.IMU_SENSOR = ""
_C.TRAIN.REPEAT_SINGLE_SENSOR = 1
_C.TRAIN.SHUFFLE_VIDEO_IN_BATCH = False
_C.TRAIN.FREEZE_BACKBONE_EPOCHS = 5
_C.TRAIN.LR_BACKBONE = 5e-4
_C.TRAIN.LR_HEADS = 5e-4
_C.TRAIN.WEIGHT_DECAY = 1e-3
_C.TRAIN.MAX_GRAD_NORM = 1.0
_C.TRAIN.TEMPERATURE = 0.07
_C.TRAIN.LEARN_TEMPERATURE = False
_C.TRAIN.CONTRASTIVE_TARGET = "pair"
_C.TRAIN.BEST_METRIC = "auto"
_C.TRAIN.IMU_NOISE_STD = 0.01
_C.TRAIN.IMU_DROPOUT_PROB = 0.05
_C.TRAIN.SKEL_NOISE_STD = 0.005
_C.TRAIN.JOINT_DROPOUT_PROB = 0.05
_C.TRAIN.ADAPTER_TRAIN_ONLY = False
_C.TRAIN.EARLY_STOP_PATIENCE = 0
_C.TRAIN.EARLY_STOP_MIN_DELTA = 0.001
_C.TRAIN.DEVICE = "cuda"
_C.TRAIN.LOG_INTERVAL = 20
_C.TRAIN.MAX_STEPS_PER_EPOCH = 0
_C.TRAIN.SAVE_EVERY_EPOCH = False
_C.TRAIN.SEED = 42
_C.TRAIN.DOMAIN_LOSS_WEIGHT = 0.0
_C.TRAIN.DOMAIN_ALPHA = 1.0
_C.TRAIN.DOMAIN_SCHEDULE = False
_C.TRAIN.DOMAIN_LABEL_MAP = "egohumans:0,custom:1"
_C.TRAIN.ID_LOSS_WEIGHT = 0.0
_C.TRAIN.PAIR_LOSS_WEIGHT = 0.0
_C.TRAIN.PAIR_LOSS_TARGET = "subject"
_C.TRAIN.PAIR_ANTI_TIE_WEIGHT = 0.0
_C.TRAIN.GROUP_BATCH_BY_WINDOW = False
_C.TRAIN.CROSS_PAIR_TRAIN_ONLY = False

_C.TRAIN.OUTPUT = CN()
_C.TRAIN.OUTPUT.OUTPUT_ROOT = ""
_C.TRAIN.OUTPUT.RUN_NAME = ""

_C.TRAIN.MODEL = CN()
_C.TRAIN.MODEL.TYPE = "hybrid"
_C.TRAIN.MODEL.INIT_ALIGNMENT_CKPT = ""
_C.TRAIN.MODEL.NUM_DOMAINS = 0
_C.TRAIN.MODEL.DOMAIN_HIDDEN_DIM = 256
_C.TRAIN.MODEL.HYBRID_HIDDEN = 128
_C.TRAIN.MODEL.HYBRID_SKELETON_SMOOTH = 9
_C.TRAIN.MODEL.HYBRID_SKELETON_FEATURE_MODE = "hybrid"
_C.TRAIN.MODEL.HYBRID_IMU_SMOOTH = 5
_C.TRAIN.MODEL.HYBRID_IMU_FEATURE_MODE = "raw"
_C.TRAIN.MODEL.HYBRID_IMAGE_HEIGHT = 1080.0
_C.TRAIN.MODEL.HYBRID_IMAGE_WIDTH = 1920.0
_C.TRAIN.MODEL.HYBRID_TOKEN_LAYERS = 1
_C.TRAIN.MODEL.HYBRID_TOKEN_HEADS = 4
_C.TRAIN.MODEL.HYBRID_TEMPORAL_LAYERS = 2
_C.TRAIN.MODEL.HYBRID_TEMPORAL_KERNEL = 5
_C.TRAIN.MODEL.HYBRID_TEMPORAL_MODE = "gru"
_C.TRAIN.MODEL.HYBRID_DROPOUT = 0.1
_C.TRAIN.MODEL.PAIR_HEAD = False
_C.TRAIN.MODEL.PAIR_HIDDEN_DIM = 256
_C.TRAIN.MODEL.CROSS_PAIR_HEAD = False
_C.TRAIN.MODEL.CROSS_PAIR_HIDDEN_DIM = 256

_C.TEST = CN()
_C.TEST.CHECKPOINT = ""
_C.TEST.BATCH_SIZE = 96
_C.TEST.NUM_WORKERS = 8
_C.TEST.DEVICE = ""
_C.TEST.IMU_STATS_JSON = ""

_C.TEST.OUTPUT = CN()
_C.TEST.OUTPUT.OUTPUT_ROOT = ""
_C.TEST.OUTPUT.RUN_NAME = ""

_C.TEST.METRICS = CN()
_C.TEST.METRICS.FRAME_ACC = CN()
_C.TEST.METRICS.FRAME_ACC.ENABLED = True
_C.TEST.METRICS.FRAME_ACC.SEED = 42
_C.TEST.METRICS.FRAME_ACC.SHUFFLE_MATCH = True
_C.TEST.METRICS.FRAME_ACC.SINGLETON_POLICY = "error"
_C.TEST.METRICS.FRAME_ACC.SEGMENT_ROOT = ""
_C.TEST.METRICS.FRAME_ACC.CUSTOM_IMU_ROOT = ""
_C.TEST.METRICS.FRAME_ACC.CUSTOM_IMU_SPLIT_MODE = "test"
_C.TEST.METRICS.FRAME_ACC.CUSTOM_IMU_RAW_SWAP_SESSIONS = []
_C.TEST.METRICS.FRAME_ACC.SESSIONS = ()
_C.TEST.METRICS.FRAME_ACC.WINDOW_SIZE = 100
_C.TEST.METRICS.FRAME_ACC.STRIDE = 16
_C.TEST.METRICS.FRAME_ACC.PER_WINDOW_FEATURES = False
_C.TEST.METRICS.FRAME_ACC.COSINE_WEIGHT = 0.0
_C.TEST.METRICS.FRAME_ACC.PAIR_LOGIT_WEIGHT = 1.0

_C.TEST.METRICS.GROUP_TEST = CN()
_C.TEST.METRICS.GROUP_TEST.ENABLED = True
_C.TEST.METRICS.GROUP_TEST.GROUP_SIZES = (2, 4, 6, 8, 16)
_C.TEST.METRICS.GROUP_TEST.NUM_TRIALS = 200
_C.TEST.METRICS.GROUP_TEST.CHUNK_WINDOWS = 30
_C.TEST.METRICS.GROUP_TEST.MIN_CHUNK_WINDOWS = 15
_C.TEST.METRICS.GROUP_TEST.SEED = 42
_C.TEST.METRICS.GROUP_TEST.SHUFFLE_MATCH = True
_C.TEST.METRICS.GROUP_TEST.PER_SUBJECT_SPLIT = False


def get_cfg_defaults() -> CN:
    """Return a fresh mutable copy of defaults."""
    return _C.clone()
